version: "3.8"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - ./_data/minio:/data

  server:
    build:
      context: ./server
    env_file: .env
    ports: ["8080:8080"]
    depends_on: [redis, minio]